### ISSUE TITLE
database ??

### ISSUE THREAD

**Issue by mlotfi2005** [harsla/fullstack_bp#2]
Hi,

1) Can you please help us understand how to fill this file secrets.js ?

module.exports = {

  db: process.env.MONGODB || 'mongodb://localhost/## YOUR_DATABASE_NAME ##',
  jwt: process.env.JWT || 'SUPERSECUREJWTSEED',
  smtpuser: process.env.SMTPUSER || 'SENDGRID_USERNAME',
  smtppassword: process.env.SMTPPASSWORD || 'SENDGRID_PASSWORD',
  company: process.env.COMPANY || 'YOURCOMPANYNAME'

  };

should we create a mongodb database ?
what are these 
SUPERSECUREJWTSEED
SMTPUSER
SENDGRID_USERNAME
SMTPPASSWORD
SENDGRID_PASSWORD
?

2) node server.js
###### 
# 
# !!! MONGOOSE WARNING !!!
# 
# This is an UNSTABLE release of Mongoose.
# Unstable releases are available for preview/testing only.
# DO NOT run this in production.
# 
###### 

module.js:340
    throw err;
          ^
Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\alotfi\UIs\0MeanStack\fullstack_bp-master\models\user.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Thanks

**Comment by harsla** [comment]
> should we create a mongodb database ?

You will need to have mongodb installed and create a database to store the users in. Once you have the database you can put in the connection string. 

>what are these ...

>SUPERSECUREJWTSEED

This is just a string the bcrypt uses to encrypt the data. Just pick something unique and make sure you don't put it on github =)

>SMTPUSER
 SENDGRID_USERNAME
 SMTPPASSWORD
 SENDGRID_PASSWORD

These credentials are giving when you sign up for a free [sendgrid](https://sendgrid.com/) account, the app uses it to send registration and reset password emails. 


>2) node server.js
... mongoose things ...
Error: Cannot find module 'bcrypt'
...

It looks like you are missing bcrypt and I had an old version of mongoose in the package.json file (I just updated it). Try running `npm install` from the project directory and see if that gets rid of the error. 

Let me know if anything else comes up!

**Comment by mlotfi2005** [comment]
Hi,
Thanks for replying to my question, I updated the package.json as you said, but got this 

C:\Users\alotfi\UIs\0MeanStack\fullstack_bp-master\node_modules\bcrypt {git}
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.3.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:645:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:753:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\alotfi\UIs\0MeanStack\fullstack_bp-master\node_modules\bcrypt
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/addressparser
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/xtend
npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd C:\Users\alotfi\UIs\0MeanStack\fullstack_bp-master
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE

Thanks, your help is appreciated.

**Comment by harsla** [comment]
Looks like a node-gyp problem, which does not work in python 3. You will need to tell npm where to find your python 2 install `npm config set python /path/to/executable/python2.7`

You will likely have this problem with any node package that uses a gyp dependency.

**Comment by mlotfi2005** [comment]
Hi,
I just installed python2.7

It's working now.
how to set it so when a user signup it will be send to my gmail ?
how to sign in as admin ?
Thanks.

**Comment by harsla** [comment]
If you were looking to send an email to yourslef when a user signs up to a designated address you could add another sendgrid call to the [auth controller](https://github.com/harsla/fullstack_bp/blob/master/controllers/auth.js#L116)

I am still working on groups and roles, so for now you will need to edit the admin flag in the database to make a user an admin.

**Comment by mlotfi2005** [comment]
How to edit the admin flag ? and where ? I did not see it when I opened the schema 
http://s13.postimg.org/dei2hv8zr/image.png

**Comment by harsla** [comment]
Sorry I must have missed the comment on this one =/ If anyone is still interested: On the user record in the database add 'admin' to the groups array. The piece middleware that check this is in [./lib/acl:](https://github.com/harsla/fullstack_bp/blob/master/lib/acl.js)

``` javascript
var roles = {
    'admin': 1,
    'user': 2
};

// find the users highest role, and see if it has access
// to the resource.
var requires_role = function (path, user) {
    var role = _.min(_.map(user.groups, function (item) {
        return roles[item];
    }));
```
